"""Add first_name and last_name to User model

Revision ID: b8e67534e2da
Revises: 
Create Date: 2025-04-18 13:02:30.997120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e67534e2da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.drop_column('valid_until')
        batch_op.drop_column('valid_from')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_details', sa.String(length=100), nullable=True))
        batch_op.alter_column('shipping_address',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('payment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('shipping_address',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('payment_details')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('payment_status')

    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valid_from', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('valid_until', sa.DATETIME(), nullable=False))

    # ### end Alembic commands ###
